services:
    _defaults:
        public: '%public.services%'

    hbpf.providers.oauth1_provider:
        class: Hanaboso\PipesPhpSdk\Authorization\Provider\OAuth1Provider
        arguments:
            - '@doctrine_mongodb.odm.default_document_manager'
            - '%backendHost%'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]

    hbpf.providers.oauth2_provider:
        class: Hanaboso\PipesPhpSdk\Authorization\Provider\OAuth2Provider
        arguments:
            - '%backendHost%'
        calls:
            - ['setLogger', ['@monolog.logger.commons']]
